
#ifndef CONFIG_SPIMCTRL
#define CONFIG_SPIMCTRL 0
#endif

#ifndef CONFIG_SPIMCTRL_READCMD
#define CONFIG_SPIMCTRL_READCMD 0
#endif

#ifndef CONFIG_SPIMCTRL_DUMMYBYTE
#define CONFIG_SPIMCTRL_DUMMYBYTE 0
#endif

#ifndef CONFIG_SPIMCTRL_DUALOUTPUT
#define CONFIG_SPIMCTRL_DUALOUTPUT 0
#endif

#ifndef CONFIG_SPIMCTRL_QUADOUTPUT
#define CONFIG_SPIMCTRL_QUADOUTPUT 0
#endif

#ifndef CONFIG_SPIMCTRL_DUALINPUT
#define CONFIG_SPIMCTRL_DUALINPUT 0
#endif

#ifndef CONFIG_SPIMCTRL_QUADINPUT
#define CONFIG_SPIMCTRL_QUADINPUT 0
#endif

#ifndef CONFIG_SPIMCTRL_DSPI
#define CONFIG_SPIMCTRL_DSPI 0
#endif

#ifndef CONFIG_SPIMCTRL_QSPI
#define CONFIG_SPIMCTRL_QSPI 0
#endif

#ifndef CONFIG_SPIMCTRL_DUMMYCYCLES
#define CONFIG_SPIMCTRL_DUMMYCYCLES 0
#endif

#ifndef CONFIG_SPIMCTRL_EXTADDR
#define CONFIG_SPIMCTRL_EXTADDR 0
#endif

#ifndef CONFIG_SPIMCTRL_SCALER
#define CONFIG_SPIMCTRL_SCALER 1
#endif

#ifndef CONFIG_SPIMCTRL_ASCALER
#define CONFIG_SPIMCTRL_ASCALER 1
#endif

#ifndef CONFIG_SPIMCTRL_PWRUPCNT
#define CONFIG_SPIMCTRL_PWRUPCNT 0
#endif

#ifndef CONFIG_SPIMCTRL_OFFSET
#define CONFIG_SPIMCTRL_OFFSET 0
#endif

#ifndef CONFIG_SPIMCTRL_RECONF
#define CONFIG_SPIMCTRL_RECONF 0
#endif