#ifndef CONFIG_NANDFCTRL_ENABLE
#define CONFIG_NANDFCTRL_ENABLE 0
#endif

#ifndef CONFIG_NANDFCTRL_NTARGETS
#define CONFIG_NANDFCTRL_NTARGETS 2
#endif

#ifndef CONFIG_NANDFCTRL_NLANES
#define CONFIG_NANDFCTRL_NLANES 8
#endif

#ifndef CONFIG_NANDFCTRL_PSIZE
#define CONFIG_NANDFCTRL_PSIZE 4096
#endif

#ifndef CONFIG_NANDFCTRL_SSIZE
#define CONFIG_NANDFCTRL_SSIZE 256
#endif

#ifndef CONFIG_NANDFCTRL_TM1
#define CONFIG_NANDFCTRL_TM1 0
#endif

#ifndef CONFIG_NANDFCTRL_TM2
#define CONFIG_NANDFCTRL_TM2 0
#endif

#ifndef CONFIG_NANDFCTRL_TM3
#define CONFIG_NANDFCTRL_TM3 0
#endif
