-----------------------------------------------------------------------------
--  LEON3 Demonstration design test bench
--  Copyright (C) 2022 Cobham Gaisler
------------------------------------------------------------------------------
--  This file is a part of the GRLIB VHDL IP LIBRARY
--  Copyright (C) 2003 - 2008, Gaisler Research
--  Copyright (C) 2008 - 2014, Aeroflex Gaisler
--  Copyright (C) 2015 - 2023, Cobham Gaisler
--  Copyright (C) 2023 - 2026, Frontgrade Gaisler
--
--  This program is free software; you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation; version 2.
--
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with this program; if not, write to the Free Software
--  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
library gaisler;
use gaisler.libdcom.all;
use gaisler.sim.all;
library techmap;
use techmap.gencomp.all;
use work.debug.all;

use work.config.all;

library nexus_sim;
use nexus_sim.all;

entity testbench is
  generic (
    fabtech   : integer := CFG_FABTECH;
    memtech   : integer := CFG_MEMTECH;
    padtech   : integer := CFG_PADTECH;
    ncpu      : integer := CFG_NCPU;
    disas     : integer := CFG_DISAS;   -- Enable disassembly to console
    dbguart   : integer := 0; --fixme CFG_DUART;        -- Print UART on console
    pclow     : integer := CFG_PCLOW;
    clkperiod : integer := 10  -- oscillator clock period in ns - 100 MHz
    );
end;

architecture behav of testbench is
  constant promfile  : string  := "prom.srec";      -- rom contents
  constant ramfile   : string := "ram.srec"; -- ram contents

  -- Number of nanoseconds of propagation delay from memory controller
  -- to memory and from memory to memory controller. Values taken from
  -- example-testbench from Lattice generated by Radiant. Without these
  -- delays the WL (write-latency) is not even nearly fulfilled and the
  -- read-training fails.
  --
  -- In that testbench there are two write delay parameters
  --   DDR3_MEM00_WR_DQS_DEL  and  DDR3_MEM00_WR_DQ_DMI_DEL
  -- both defined to have the value
  --   `DDR3_GEAR4_DELAY*27*1000000/`MEMCLK_FREQ
  -- There are also two read delay parameters
  --   DDR3_MEM00_RD_DQ_DMI_DEL  and  DDR3_MEM00_RD_DQS_DEL
  -- with the value
  --   `DDR3_GEAR4_DELAY*8*1000000/`MEMCLK_FREQ
  --
  -- `define MEMCLK_FREQ 400.0
  -- `define DDR3_GEAR4_DELAY     (`GEAR-1.75)/2
  -- `define GEAR 4
  --
  -- The unit for the above quantities is 0.1 ps. Here we use ns as the
  -- unit instead, because that is what gaisler.sim.delay_wire uses.
  constant delay_mc2mem : real := 7.60;
  constant delay_mem2mc : real := 2.25;

  constant ct       : integer := clkperiod/2;

  signal clk_in     : std_logic := '0';
  signal gsrn       : std_logic := '0';

  signal led        : std_logic_vector(7 downto 0);
  signal pmod0      : std_logic_vector(7 downto 0);
  signal dip_sw     : std_logic_vector(3 downto 0);

  signal spi_mclk   : std_logic;
  signal dq0_mosi   : std_logic;
  signal dq1_miso   : std_logic;
  signal csspin     : std_logic;
  signal dq2        : std_logic;
  signal dq3        : std_logic;

  signal rxduart : std_logic;
  signal txduart : std_logic;

  signal error   : std_logic;

  --signal ddr3_dq   : std_logic_vector(15 downto 0);
  --signal ddr3_dqs, ddr3_dqsn  : std_logic_vector(1 downto 0);
  --signal ddr3_dm   : std_logic_vector(1 downto 0);
  --ddr3_nu -- not used because TDQS is disabled
  -- DDR3 address/control
  signal ddr3_addr   : std_logic_vector(12 downto 0);
  signal ddr3_ba     : std_logic_vector(2 downto 0);
  signal ddr3_cke    : std_logic_vector(0 downto 0);
  signal ddr3_cke_l  : std_logic;
  signal ddr3_ck     : std_logic_vector(0 downto 0);
  signal ddr3_ck_l   : std_logic;
  signal ddr3_ckn_l  : std_logic;
  signal ddr3_csn    : std_logic_vector(0 downto 0);
  signal ddr3_csn_l  : std_logic;
  signal ddr3_odt    : std_logic_vector(0 downto 0);
  signal ddr3_odt_l  : std_logic;
  signal ddr3_casn   : std_logic;
  signal ddr3_rasn   : std_logic;
  signal ddr3_wen    : std_logic;
  signal ddr3_resetn : std_logic;

  -- The memory controller requires a propagation delay of about 7.5 ns
  -- between the control ines (synchronous to CK) and the data lines
  -- (DQ, DQS, and DM).
  signal ddr3_dq_mc, ddr3_dq_mem : std_logic_vector(15 downto 0);
  signal ddr3_dqs_mc, ddr3_dqsn_mc, ddr3_dqs_mem, ddr3_dqsn_mem : std_logic_vector(1 downto 0);
  signal ddr3_dm_mc, ddr3_dm_mem : std_logic_vector(1 downto 0);
  -- Also delay ODT?

  type int_arr is array(natural range <>) of integer;
  constant ddr3_arr     : int_arr(0 to 6) := (  1,  1,  0,  0,  0,  1,  1);
  constant speedbin_arr : int_arr(0 to 6) := (  0,  9,  0,  6,  0,  2,  0);
  constant sysfreq_arr  : int_arr(0 to 6) := (333,800,200,400,133,500,400);

  constant memtype     : integer := 5;
  constant memspeedbin : integer := 13;--speedbin_arr(memtype);

  component ddr3 is
    port (
      rst_n: in std_logic;
      ck: in std_logic;
      ck_n : in std_logic;
      cke: in std_logic;
      cs_n: in std_logic;
      ras_n: in std_logic;
      cas_n: in std_logic;
      we_n: in std_logic;
      dm_tdqs: inout std_logic_vector(1 downto 0);
      ba: in std_logic_vector(2 downto 0);
      addr: in std_logic_vector(12 downto 0);
      dq: inout std_logic_vector(15 downto 0);
      dqs: inout std_logic_vector(1 downto 0);
      dqs_n: inout std_logic_vector(1 downto 0);
      tdqs_n: inout std_logic_vector(1 downto 0);
      odt: in std_logic
      );
  end component;

begin
  -- clock and reset
  clk_in      <= not clk_in after ct * 1 ns;--ct=4ns
  gsrn        <= '0', '1' after ct * 55 ns;

  rxduart     <= 'H';

  d3 : entity work.leon3mp
    generic map (fabtech => fabtech,
                 memtech => memtech,
                 padtech => padtech,
                 dbguart => 0,
                 simulation => false,
                 ramfile => ramfile)
    port map (
      clk_in   => clk_in,
      gsrn     => gsrn,
      led      => led,
      pmod0    => pmod0,
      dip_sw   => dip_sw,
      spi_mclk => spi_mclk,
      dq0_mosi => dq0_mosi,
      dq1_miso => dq1_miso,
      csspin   => csspin,
      dq2      => dq2,
      dq3      => dq3,
      rxduart  => rxduart,
      txduart  => txduart,
      can_tx   => open,
      can_rx   => '0',
      can_en   => open,
      -- DDR3 memory
      ddr3_dq  => ddr3_dq_mc,
      ddr3_dqs => ddr3_dqs_mc,
      ddr3_dm  => ddr3_dm_mc,
      --ddr3_nu -- not used because TDQS is disabled
      -- DDR3 address/control (no delay on these)
      ddr3_addr => ddr3_addr,
      ddr3_ba   => ddr3_ba,
      ddr3_cke  => ddr3_cke,
      ddr3_ck   => ddr3_ck,
      ddr3_csn  => ddr3_csn,
      ddr3_odt  => ddr3_odt,
      ddr3_casn => ddr3_casn,
      ddr3_rasn => ddr3_rasn,
      ddr3_wen  => ddr3_wen,
      ddr3_resetn => ddr3_resetn
      );

  -- No delay on clock or control signals
  ddr3_ck_l <= ddr3_ck(0);
  ddr3_ckn_l <= not ddr3_ck(0);
  ddr3_cke_l <= ddr3_cke(0);
  ddr3_csn_l <= ddr3_csn(0);
  ddr3_odt_l <= ddr3_odt(0);

  -- But on data pins the controller expects delay. In fact the delay
  -- is asymmetric. It is longer (7.60 ns) from MC to MEM compated to
  -- MEM to MC (2.25 ns). Unclear where these huge delays come from.
  board_delay_dq : delay_wire
    generic map(
      data_width => 16,
      delay_atob => delay_mc2mem,
      delay_btoa => delay_mem2mc)
    port map (
      a => ddr3_dq_mc,
      b => ddr3_dq_mem);

  board_delay_dqs : delay_wire
    generic map(
      data_width => 2,
      delay_atob => delay_mc2mem,
      delay_btoa => delay_mem2mc)
    port map (
      a => ddr3_dqs_mc,
      b => ddr3_dqs_mem);

  board_delay_dm : delay_wire
    generic map(
      data_width => 2,
      delay_atob => delay_mc2mem,
      delay_btoa => delay_mem2mc)
    port map (
      a => ddr3_dm_mc,
      b => ddr3_dm_mem);

  -- Not required. The memory model looks only at dqs, not dqsn
  --ddr3_dqsn_mc <= not ddr3_dqs_mc;

  -- ram_micron: ddr3
  --   port map(
  --     rst_n => ddr3_resetn,
  --     ck => ddr3_ck_l,
  --     ck_n => ddr3_ckn_l,
  --     cke => ddr3_cke_l,
  --     cs_n => ddr3_csn_l,
  --     ras_n => ddr3_rasn,
  --     cas_n => ddr3_casn,
  --     we_n => ddr3_wen,
  --     dm_tdqs => ddr3_dm,
  --     ba => ddr3_ba,
  --     addr => ddr3_addr,
  --     dq => ddr3_dq,
  --     dqs => ddr3_dqs,
  --     dqs_n => ddr3_dqsn,
  --     tdqs_n => open,
  --     odt => ddr3_odt_l
  --     );


  ram0: ddr3ram
    generic map (
      width => 16,
      abits => 13,
      fname => "ram.srec",
      colbits => 10,
      rowbits => 13,  -- Use less rowbits to save RAM
      speedbin => memspeedbin,
      implbanks => 8,
      initbyte => 16#33#)
    port map (
      ck => ddr3_ck_l,
      ckn => ddr3_ckn_l,
      cke => ddr3_cke_l,
      csn => ddr3_csn_l,
      odt => ddr3_odt_l,
      rasn => ddr3_rasn,
      casn => ddr3_casn,
      wen => ddr3_wen,
      dm => ddr3_dm_mem, -- delayed
      ba => ddr3_ba,
      a => ddr3_addr,
      resetn => ddr3_resetn,
      -- Delayed data signals (clock/control are not delayed)
      dq => ddr3_dq_mem,
      dqs => ddr3_dqs_mem,
      dqsn => ddr3_dqsn_mem);

  s0 : spi_flash
    generic map (ftype => 4, debug => 0, fname => promfile,
                 readcmd => CFG_SPIMCTRL_READCMD,
                 dummybyte => CFG_SPIMCTRL_DUMMYBYTE,
                 dualoutput => CFG_SPIMCTRL_DUALOUTPUT)
    port map (spi_mclk, dq0_mosi, dq1_miso, csspin);

  error <= led(0);

  iuerr : process
  begin
    wait for 5 us;
    if to_x01(error) = '0' then wait on error; end if;
    assert (to_X01(error) = '0')
      report "*** IU in error mode, simulation halted ***"
      severity failure;
  end process;

end;
