/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
/*
 * Synthesis      
 */
#undef  CONFIG_SYN_INFERRED
#undef  CONFIG_SYN_AXCEL
#undef  CONFIG_SYN_AXDSP
#undef  CONFIG_SYN_FUSION
#undef  CONFIG_SYN_PROASIC
#undef  CONFIG_SYN_PROASICPLUS
#undef  CONFIG_SYN_PROASIC3
#undef  CONFIG_SYN_PROASIC3E
#undef  CONFIG_SYN_PROASIC3L
#undef  CONFIG_SYN_IGLOO
#undef  CONFIG_SYN_IGLOO2
#undef  CONFIG_SYN_SF2
#undef  CONFIG_SYN_RTG4
#undef  CONFIG_SYN_POLARFIRE
#undef  CONFIG_SYN_UT130HBD
#undef  CONFIG_SYN_UT90NHBD
#undef  CONFIG_SYN_CYCLONEIII
#undef  CONFIG_SYN_STRATIX
#undef  CONFIG_SYN_STRATIXII
#undef  CONFIG_SYN_STRATIXIII
#undef  CONFIG_SYN_STRATIXIV
#undef  CONFIG_SYN_STRATIXV
#define CONFIG_SYN_ALTERA 1
#undef  CONFIG_SYN_ATC18
#undef  CONFIG_SYN_ATC18RHA
#undef  CONFIG_SYN_CUSTOM1
#undef  CONFIG_SYN_DARE
#undef  CONFIG_SYN_CMOS9SF
#undef  CONFIG_SYN_NEXUS
#undef  CONFIG_SYN_BRAVEMED
#undef  CONFIG_SYN_ECLIPSE
#undef  CONFIG_SYN_RH_LIB18T
#undef  CONFIG_SYN_RHUMC
#undef  CONFIG_SYN_RHS65
#undef  CONFIG_SYN_SAED32
#undef  CONFIG_SYN_SMIC13
#undef  CONFIG_SYN_TM65GPLUS
#undef  CONFIG_SYN_TSMC90
#undef  CONFIG_SYN_UMC
#undef  CONFIG_SYN_ARTIX7
#undef  CONFIG_SYN_KINTEX7
#undef  CONFIG_SYN_KINTEXU
#undef  CONFIG_SYN_SPARTAN3
#undef  CONFIG_SYN_SPARTAN3E
#undef  CONFIG_SYN_SPARTAN6
#undef  CONFIG_SYN_VIRTEX2
#undef  CONFIG_SYN_VIRTEX4
#undef  CONFIG_SYN_VIRTEX5
#undef  CONFIG_SYN_VIRTEX6
#undef  CONFIG_SYN_VIRTEX7
#undef  CONFIG_SYN_ZYNQ7000
#undef  CONFIG_SYN_INFER_RAM
#undef  CONFIG_SYN_INFER_PADS
#undef  CONFIG_SYN_NO_ASYNC
#undef  CONFIG_SYN_SCAN
/*
 * LEON5 Processor system
 */
#define CONFIG_PROC_NUM (1)
#define CONFIG_FPU_NANOFPU 1
#undef  CONFIG_FPU_GRFPU5
#define CONFIG_LEON5_HP 1
#undef  CONFIG_LEON5_GP
#undef  CONFIG_LEON5_EP
#define CONFIG_LEON5_PERFCFG (0)
#define CONFIG_LEON5_RF_0 1
#undef  CONFIG_LEON5_RF_1
#define CONFIG_LEON5_RFCFG (0)
/*
 * Cache memory Configuration  
 */
#define CONFIG_LEON5_CMCFG_TAG (0)
#define CONFIG_LEON5_CMCFG_DATA (0)
/*
 * Tightly coupled memory      
 */
#define CONFIG_LEON5_ITCM_NONE 1
#undef  CONFIG_LEON5_ITCM_1K
#undef  CONFIG_LEON5_ITCM_2K
#undef  CONFIG_LEON5_ITCM_4K
#undef  CONFIG_LEON5_ITCM_8K
#undef  CONFIG_LEON5_ITCM_16K
#undef  CONFIG_LEON5_ITCM_32K
#undef  CONFIG_LEON5_ITCM_64K
#undef  CONFIG_LEON5_ITCM_128K
#undef  CONFIG_LEON5_ITCM_256K
#undef  CONFIG_LEON5_ITCM_512K
#undef  CONFIG_LEON5_ITCM_1M
#define CONFIG_LEON5_DTCM_NONE 1
#undef  CONFIG_LEON5_DTCM_1K
#undef  CONFIG_LEON5_DTCM_2K
#undef  CONFIG_LEON5_DTCM_4K
#undef  CONFIG_LEON5_DTCM_8K
#undef  CONFIG_LEON5_DTCM_16K
#undef  CONFIG_LEON5_DTCM_32K
#undef  CONFIG_LEON5_DTCM_64K
#undef  CONFIG_LEON5_DTCM_128K
#undef  CONFIG_LEON5_DTCM_256K
#undef  CONFIG_LEON5_DTCM_512K
#undef  CONFIG_LEON5_DTCM_1M
#define CONFIG_LEON5_ITCMCFG (0)
#define CONFIG_LEON5_DTCMCFG (0)
/*
 * Fault-tolerance  
 */
#define CONFIG_IUFT_NONE 1
#undef  CONFIG_IUFT_TECHSPEC
#undef  CONFIG_IUFT_RTL
#define CONFIG_CACHE_FT_NONE 1
#undef  CONFIG_CACHE_FT_TECHSPEC
#undef  CONFIG_CACHE_FT_RTL
#define CONFIG_LEON5_RF_FTCFG (0)
#define CONFIG_LEON5_CACHE_FTCFG (0)
#undef  CONFIG_AHB_32BIT
#define CONFIG_AHB_64BIT 1
#undef  CONFIG_AHB_128BIT
#define CONFIG_BWMASK 00f0
#define CONFIG_CACHE_FIXED 0
/*
 * Debug Link           
 */
#define CONFIG_DSU_UART 1
#define CONFIG_DSU_JTAG 1
#define CONFIG_DSU_ETH 1
#undef  CONFIG_DSU_ETHSZ1
#define CONFIG_DSU_ETHSZ2 1
#undef  CONFIG_DSU_ETHSZ4
#undef  CONFIG_DSU_ETHSZ8
#undef  CONFIG_DSU_ETHSZ16
#define CONFIG_DSU_IPMSB C0A8
#define CONFIG_DSU_IPLSB 0033
#define CONFIG_DSU_ETHMSB 020000
#define CONFIG_DSU_ETHLSB 000000
#undef  CONFIG_DSU_ETH_PROG
/*
 * Peripherals             
 */
/*
 * Memory controllers             
 */
/*
 * Synchronous SRAM controller   
 */
#undef  CONFIG_SSCTRL
#define CONFIG_I2C_ENABLE 1
/*
 * On-chip RAM/ROM                 
 */
#define CONFIG_AHBROM_ENABLE 1
#define CONFIG_AHBROM_START 000
#undef  CONFIG_AHBROM_PIPE
#undef  CONFIG_AHBRAM_ENABLE
/*
 * Ethernet             
 */
#define CONFIG_GRETH_ENABLE 1
#undef  CONFIG_GRETH_GIGA
#undef  CONFIG_GRETH_FIFO4
#define CONFIG_GRETH_FIFO8 1
#undef  CONFIG_GRETH_FIFO16
#undef  CONFIG_GRETH_FIFO32
#undef  CONFIG_GRETH_FIFO64
#undef  CONFIG_GRETH_FMC_MODE
#define CONFIG_GRETH_PHY_ADDR (1)
#define CONFIG_GRETH2_ENABLE 1
#undef  CONFIG_GRETH2_GIGA
#undef  CONFIG_GRETH2_FIFO4
#define CONFIG_GRETH2_FIFO8 1
#undef  CONFIG_GRETH2_FIFO16
#undef  CONFIG_GRETH2_FIFO32
#undef  CONFIG_GRETH2_FIFO64
/*
 * UARTs, timers and irq control         
 */
#define CONFIG_UART1_ENABLE 1
#undef  CONFIG_UA1_FIFO1
#undef  CONFIG_UA1_FIFO2
#undef  CONFIG_UA1_FIFO4
#define CONFIG_UA1_FIFO8 1
#undef  CONFIG_UA1_FIFO16
#undef  CONFIG_UA1_FIFO32
#define CONFIG_IRQ3_ENABLE 1
#undef  CONFIG_IRQ3_SEC
#define CONFIG_GPT_ENABLE 1
#define CONFIG_GPT_NTIM (2)
#define CONFIG_GPT_SW (8)
#define CONFIG_GPT_TW (32)
#define CONFIG_GPT_IRQ (8)
#define CONFIG_GPT_SEPIRQ 1
#undef  CONFIG_GPT_WDOGEN
#define CONFIG_GRGPIO_ENABLE 1
#define CONFIG_GRGPIO_WIDTH (2)
#define CONFIG_GRGPIO_IMASK 000F
/*
 * VHDL Debugging        
 */
#undef  CONFIG_IU_DISAS
#undef  CONFIG_AHB_DTRACE
