#ifndef CONFIG_GRVERSION_ENABLE
#define CONFIG_GRVERSION_ENABLE 0
#endif
#ifndef CONFIG_GRVERSION_VERSION
#define CONFIG_GRVERSION_VERSION 0000
#endif
#ifndef CONFIG_GRVERSION_REVISION
#define CONFIG_GRVERSION_REVISION 0000
#endif

