
#ifndef CONFIG_CMP7GRLIB
#define CONFIG_CMP7GRLIB 0
#endif

#ifndef CONFIG_CMP7GRLIB_DEBUG
#define CONFIG_CMP7GRLIB_DEBUG 0
#endif

#ifndef CONFIG_CMP7GRLIB_SYNCFIQ
#define CONFIG_CMP7GRLIB_SYNCFIQ 0
#endif

#ifndef CONFIG_CMP7GRLIB_SYNCIRQ
#define CONFIG_CMP7GRLIB_SYNCIRQ 0
#endif
